# Generated by Django 5.1.6 on 2025-02-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('productivity', models.FloatField()),
                ('skills', models.TextField()),
                ('years_of_experience', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('present_tasks', models.TextField()),
                ('present_project', models.CharField(max_length=100)),
                ('nearest_deadline', models.DateField()),
            ],
        ),
    ]
